// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/microuser/microuser.proto

package microuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Microuser service

func NewMicrouserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Microuser service

type MicrouserService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microuser_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Microuser_PingPongService, error)
}

type microuserService struct {
	c    client.Client
	name string
}

func NewMicrouserService(name string, c client.Client) MicrouserService {
	return &microuserService{
		c:    c,
		name: name,
	}
}

func (c *microuserService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Microuser.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microuserService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microuser_StreamService, error) {
	req := c.c.NewRequest(c.name, "Microuser.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microuserServiceStream{stream}, nil
}

type Microuser_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microuserServiceStream struct {
	stream client.Stream
}

func (x *microuserServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microuserServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microuserServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microuserServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microuserServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microuserService) PingPong(ctx context.Context, opts ...client.CallOption) (Microuser_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Microuser.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microuserServicePingPong{stream}, nil
}

type Microuser_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microuserServicePingPong struct {
	stream client.Stream
}

func (x *microuserServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microuserServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *microuserServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microuserServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microuserServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microuserServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Microuser service

type MicrouserHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Microuser_StreamStream) error
	PingPong(context.Context, Microuser_PingPongStream) error
}

func RegisterMicrouserHandler(s server.Server, hdlr MicrouserHandler, opts ...server.HandlerOption) error {
	type microuser interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Microuser struct {
		microuser
	}
	h := &microuserHandler{hdlr}
	return s.Handle(s.NewHandler(&Microuser{h}, opts...))
}

type microuserHandler struct {
	MicrouserHandler
}

func (h *microuserHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicrouserHandler.Call(ctx, in, out)
}

func (h *microuserHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicrouserHandler.Stream(ctx, m, &microuserStreamStream{stream})
}

type Microuser_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microuserStreamStream struct {
	stream server.Stream
}

func (x *microuserStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microuserStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microuserStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microuserStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microuserStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microuserHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicrouserHandler.PingPong(ctx, &microuserPingPongStream{stream})
}

type Microuser_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microuserPingPongStream struct {
	stream server.Stream
}

func (x *microuserPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microuserPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microuserPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microuserPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microuserPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microuserPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
